#ifndef ID_H
#define ID_H

//Main
#define			ID_MAIN_BUTTON_NEW_MAP				10001
#define			ID_MAIN_BUTTON_LOAD_MAP				10002
#define			ID_MAIN_BUTTON_SAVE_MAP				10003
#define			ID_MAIN_BUTTON_SETTINGS				10004
#define			ID_MAIN_BUTTON_PARTICLE_SYS_CREATOR	10005
#define			ID_MAIN_BUTTON_OBJECTS_CREATOR		10006

#endif ID_H
